# Site settings
title:        "things"
description:  I have never known what to call my blog. It has things in it though, so I went with that.
keywords:     Phillip Chaffee Blog Programming Technology Thoughts Ideas
language:     "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:      "/" # the subpath of your site, e.g. /blog
url:          "http://phillipchaffee.io" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:    /blog/:categories/:title

# Markdown Processor
markdown:     kramdown